export const CLOUD_LOGIN_ENDPOINT = '/auth/login';
export const CLOUD_REVENUE_CHART_ENDPOINT = '/dashboard/chart';
export const CLOUD_SALE_BRAND_CHART_ENDPOINT = '/dashboard/summary-sale-by-brand';
export const CLOUD_TOP_PRODUCTS_ENDPOINT = '/dashboard/top-product';
export const CLOUD_SALE_PROVINCE_CHART_ENDPOINT = '/dashboard/summary-sale-by-province';
export const CLOUD_NEARLY_SOLD_OUT_CHART_ENDPOINT = '/dashboard/nearly-sold-out';

export const CLOUD_ORDER_ENDPOINT = '/order';
export const CLOUD_ORDER_LIST_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/list`;
export const CLOUD_ORDER_LIST_EXPORT_ENDPOINT = 'report/misa/export';
export const CLOUD_ORDER_DETAIL_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/get`;
export const CLOUD_ORDER_ADD_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/add`;
export const CLOUD_ORDER_UPDATE_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/update`;
export const CLOUD_ORDER_CHECK_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/check-order`;
export const CLOUD_ORDER_DOWNLOAD_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/download`;
export const CLOUD_ORDER_VOID_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/void`;
export const CLOUD_ORDER_QUICK_EXPORT_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/quick-export`;
export const CLOUD_ORDER_SEARCH_ENDPOINT = `${CLOUD_ORDER_ENDPOINT}/search`;

export const CLOUD_WAREHOUSE_ENDPOINT = '/warehouse';
export const CLOUD_WAREHOUSE_LIST_ENDPOINT = `${CLOUD_WAREHOUSE_ENDPOINT}/list`;
export const CLOUD_WAREHOUSE_ALL_ENDPOINT = `${CLOUD_WAREHOUSE_ENDPOINT}/all`;
export const CLOUD_WAREHOUSE_DETAIL_ENDPOINT = `${CLOUD_WAREHOUSE_ENDPOINT}/get`;
export const CLOUD_WAREHOUSE_DELETE_ENDPOINT = `${CLOUD_WAREHOUSE_ENDPOINT}/delete`;
export const CLOUD_WAREHOUSE_SAVE_ENDPOINT = `${CLOUD_WAREHOUSE_ENDPOINT}/save`;
export const CLOUD_WAREHOUSE_PRODUCTS_ENDPOINT = `${CLOUD_WAREHOUSE_ENDPOINT}/products`;
export const CLOUD_WAREHOUSE_PRODUCTS_SAVE_ENDPOINT = `${CLOUD_WAREHOUSE_PRODUCTS_ENDPOINT}/save`;

export const CLOUD_CUSTOMER_ENDPOINT = '/customer';
export const CLOUD_CUSTOMER_LIST_ENDPOINT = `${CLOUD_CUSTOMER_ENDPOINT}/list`;
export const CLOUD_CUSTOMER_SAVE_ENDPOINT = `${CLOUD_CUSTOMER_ENDPOINT}/save`;
export const CLOUD_CUSTOMER_GET_ENDPOINT = `${CLOUD_CUSTOMER_ENDPOINT}/get`;
export const CLOUD_CUSTOMER_DELETE_ENDPOINT = `${CLOUD_CUSTOMER_ENDPOINT}/delete`;
export const CLOUD_CUSTOMER_VERIFY_ENDPOINT = `${CLOUD_CUSTOMER_ENDPOINT}/verify`;
export const CLOUD_CUSTOMER_SEARCH_ENDPOINT = `${CLOUD_CUSTOMER_ENDPOINT}/search`;
export const CLOUD_CUSTOMER_EXPORT_ENDPOINT = `${CLOUD_CUSTOMER_ENDPOINT}/export`;

export const CLOUD_PRODUCT_ENDPOINT = '/product';
export const CLOUD_PRODUCT_SEARCH_ENDPOINT = `${CLOUD_PRODUCT_ENDPOINT}/search`;
export const CLOUD_PRODUCT_LIST_ENDPOINT = `${CLOUD_PRODUCT_ENDPOINT}/list`;
export const CLOUD_PRODUCT_DETAIL_ENDPOINT = `${CLOUD_PRODUCT_ENDPOINT}/get`;
export const CLOUD_PRODUCT_SAVE_ENDPOINT = `${CLOUD_PRODUCT_ENDPOINT}/save`;
export const CLOUD_PRODUCT_DELETE_ENDPOINT = `${CLOUD_PRODUCT_ENDPOINT}/delete`;
export const CLOUD_PRODUCT_EXPORT_ENDPOINT = `${CLOUD_PRODUCT_ENDPOINT}/export`;

export const CLOUD_AU_ENDPOINT = '/resource/administrative-unit';

export const CLOUD_MERCHANT_DEFAULT_ENDPOINT = '/merchant-default/list';
export const CLOUD_MERCHANT_DEFAULT_SAVE_ENDPOINT = '/merchant-default/save';

export const CLOUD_STORE_ENDPOINT = '/store';
export const CLOUD_STORE_LIST_ENDPOINT = `${CLOUD_STORE_ENDPOINT}/list`;
export const CLOUD_STORE_ALL_ENDPOINT = `${CLOUD_STORE_ENDPOINT}/all`;
export const CLOUD_STORE_DETAIL_ENDPOINT = `${CLOUD_STORE_ENDPOINT}/get`;
export const CLOUD_STORE_DELETE_ENDPOINT = `${CLOUD_STORE_ENDPOINT}/delete`;
export const CLOUD_STORE_SAVE_ENDPOINT = `${CLOUD_STORE_ENDPOINT}/save`;
export const CLOUD_STORE_PRODUCTS_ENDPOINT = `${CLOUD_STORE_ENDPOINT}/products`;
export const CLOUD_STORE_PRODUCTS_SAVE_ENDPOINT = `${CLOUD_STORE_PRODUCTS_ENDPOINT}/save`;

export const CLOUD_GLOBAL_SETTING_ENDPOINT = '/global-setting';
export const CLOUD_GLOBAL_SETTING_MERCHANT_ENDPOINT = `${CLOUD_GLOBAL_SETTING_ENDPOINT}/merchant`;

export const CLOUD_PAYMENT_METHOD_ENDPOINT = '/payment-method';
export const CLOUD_PAYMENT_METHOD_ALL_ENDPOINT = `${CLOUD_PAYMENT_METHOD_ENDPOINT}/all`;
export const CLOUD_PAYMENT_METHOD_SAVE_ENDPOINT = `${CLOUD_PAYMENT_METHOD_ENDPOINT}/save`;
export const CLOUD_PAYMENT_METHOD_DELETE_ENDPOINT = `${CLOUD_PAYMENT_METHOD_ENDPOINT}/delete`;
export const CLOUD_PAYMENT_METHOD_GET_ENDPOINT = `${CLOUD_PAYMENT_METHOD_ENDPOINT}/get`;

export const CLOUD_RP_ENDPOINT = '/receipt-payment';
export const CLOUD_RP_RECEIPT_ENDPOINT = `${CLOUD_RP_ENDPOINT}/receipt`;
export const CLOUD_RP_RECEIPT_DELETE_ENDPOINT = `${CLOUD_RP_RECEIPT_ENDPOINT}/delete`;
export const CLOUD_RP_PAYMENT_ENDPOINT = `${CLOUD_RP_ENDPOINT}/payment`;
export const CLOUD_RP_PAYMENT_DELETE_ENDPOINT = `${CLOUD_RP_PAYMENT_ENDPOINT}/delete`;
export const CLOUD_RP_RECEIPT_ORDER_ENDPOINT = `${CLOUD_RP_RECEIPT_ENDPOINT}/order`;

export const CLOUD_BRAND_ENDPOINT = '/brand';
export const CLOUD_BRAND_LIST_ENDPOINT = `${CLOUD_BRAND_ENDPOINT}/list`;
export const CLOUD_BRAND_DETAIL_ENDPOINT = `${CLOUD_BRAND_ENDPOINT}/get`;
export const CLOUD_BRAND_DELETE_ENDPOINT = `${CLOUD_BRAND_ENDPOINT}/delete`;
export const CLOUD_BRAND_SAVE_ENDPOINT = `${CLOUD_BRAND_ENDPOINT}/save`;
export const CLOUD_BRAND_PRODUCTS_ENDPOINT = `${CLOUD_BRAND_ENDPOINT}/products`;
export const CLOUD_BRAND_PRODUCTS_SAVE_ENDPOINT = `${CLOUD_BRAND_PRODUCTS_ENDPOINT}/save`;

export const CLOUD_CATEGORY_ENDPOINT = '/category';
export const CLOUD_CATEGORY_ALL_ENDPOINT = `${CLOUD_CATEGORY_ENDPOINT}/all`;
export const CLOUD_CATEGORY_LIST_ENDPOINT = `${CLOUD_CATEGORY_ENDPOINT}/list`;
export const CLOUD_CATEGORY_DETAIL_ENDPOINT = `${CLOUD_CATEGORY_ENDPOINT}/get`;
export const CLOUD_CATEGORY_SAVE_ENDPOINT = `${CLOUD_CATEGORY_ENDPOINT}/save`;
export const CLOUD_CATEGORY_DELETE_ENDPOINT = `${CLOUD_CATEGORY_ENDPOINT}/delete`;
export const CLOUD_CATEGORY_PRODUCTS_ENDPOINT = `${CLOUD_CATEGORY_ENDPOINT}/products`;
export const CLOUD_CATEGORY_PRODUCTS_SAVE_ENDPOINT = `${CLOUD_CATEGORY_PRODUCTS_ENDPOINT}/save`;

export const CLOUD_RP_LIST_ENDPOINT = `${CLOUD_RP_ENDPOINT}/list`;
export const CLOUD_RP_LIST_EXPORT_ENDPOINT = `${CLOUD_RP_LIST_ENDPOINT}/download`;
export const CLOUD_RP_PAYMENT_RECEIPT_LIST_ENDPOINT = `${CLOUD_RP_PAYMENT_ENDPOINT}/receipt`;

export const CLOUD_CUSTOMER_DEBT_ENDPOINT = '/customer-debt';
export const CLOUD_CUSTOMER_DEBT_DETAIL_ENDPOINT = '/customer-debt/debt-detail';
export const CLOUD_CUSTOMER_DEBT_TICKET_ENDPOINT = `${CLOUD_CUSTOMER_DEBT_ENDPOINT}/ticket`;

export const CLOUD_CUSTOMER_RP_ENDPOINT = '/customer-rp';

export const CLOUD_CUSTOMER_GROUP_ENDPOINT = '/customer-group';
export const CLOUD_CUSTOMER_GROUP_LIST_ENDPOINT = `${CLOUD_CUSTOMER_GROUP_ENDPOINT}/list`;
export const CLOUD_CUSTOMER_GROUP_GET_ENDPOINT = `${CLOUD_CUSTOMER_GROUP_ENDPOINT}/get`;
export const CLOUD_CUSTOMER_GROUP_SAVE_ENDPOINT = `${CLOUD_CUSTOMER_GROUP_ENDPOINT}/save`;
export const CLOUD_CUSTOMER_GROUP_DELETE_ENDPOINT = `${CLOUD_CUSTOMER_GROUP_ENDPOINT}/delete`;
export const CLOUD_CUSTOMER_GROUP_SAVE_CUSTOMERS_ENDPOINT = `${CLOUD_CUSTOMER_GROUP_ENDPOINT}/customers/save`;

export const CLOUD_REPORT_ENDPOINT = '/report';
export const CLOUD_REPORT_ORDER_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/order`;
export const CLOUD_REPORT_ORDER_EXPORT_ENDPOINT = `${CLOUD_REPORT_ORDER_ENDPOINT}/export`;
export const CLOUD_CLOUD_REPORT_CATEGORY_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/category`;
export const CLOUD_REPORT_CATEGORY_EXPORT_ENDPOINT = `${CLOUD_CLOUD_REPORT_CATEGORY_ENDPOINT}/export`;
export const CLOUD_REPORT_CUSTOMER_BY_ORDER_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/customer-by-order`;
export const CLOUD_REPORT_CUSTOMER_BY_PRODUCT_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/customer-by-product`;
export const CLOUD_REPORT_CUSTOMER_EXPORT_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/customer/export`;
export const CLOUD_REPORT_PRODUCT_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/product`;
export const CLOUD_REPORT_PRODUCT_EXPORT_ENDPOINT = `${CLOUD_REPORT_PRODUCT_ENDPOINT}/export`;
export const CLOUD_REPORT_EXPORT_STOCK_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/export-stock`;
export const CLOUD_REPORT_EXPORT_STOCK_EXPORT_ENDPOINT = `${CLOUD_REPORT_EXPORT_STOCK_ENDPOINT}/download`;
export const CLOUD_REPORT_IMPORT_STOCK_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/import-stock`;
export const CLOUD_REPORT_IMPORT_STOCK_EXPORT_ENDPOINT = `${CLOUD_REPORT_IMPORT_STOCK_ENDPOINT}/download`;
export const CLOUD_REPORT_CUSTOMER_DEBT_ENDPOINT = `${CLOUD_REPORT_ENDPOINT}/customer-debt`;
export const CLOUD_REPORT_CUSTOMER_DEBT_EXPORT_ENDPOINT = `${CLOUD_REPORT_CUSTOMER_DEBT_ENDPOINT}/download`;

export const CLOUD_SALE_ITEM_ENDPOINT = '/sale-item';
export const CLOUD_SALE_ITEM_BRAND_ENDPOINT = `${CLOUD_SALE_ITEM_ENDPOINT}/brand`;
export const CLOUD_SALE_ITEM_PRODUCT_ENDPOINT = `${CLOUD_SALE_ITEM_ENDPOINT}/product`;

export const CLOUD_SUPPLIER_ENDPOINT = '/supplier';
export const CLOUD_SUPPLIER_LIST_ENDPOINT = `${CLOUD_SUPPLIER_ENDPOINT}/list`;
export const CLOUD_SUPPLIER_DETAIL_ENDPOINT = `${CLOUD_SUPPLIER_ENDPOINT}/get`;
export const CLOUD_SUPPLIER_SAVE_ENDPOINT = `${CLOUD_SUPPLIER_ENDPOINT}/save`;
export const CLOUD_SUPPLIER_DELETE_ENDPOINT = `${CLOUD_SUPPLIER_ENDPOINT}/delete`;
export const CLOUD_SUPPLIER_ALL_ENDPOINT = `${CLOUD_SUPPLIER_ENDPOINT}/all`;

export const CLOUD_SETTINGS_ENDPOINT = '/setting';
export const CLOUD_GET_ORDER_SETTING_ENDPOINT = `${CLOUD_SETTINGS_ENDPOINT}/get-order-setting`;
export const CLOUD_SAVE_ORDER_SETTING_ENDPOINT = `${CLOUD_SETTINGS_ENDPOINT}/save-order-setting`;
export const CLOUD_CODE_SETTING_ENDPOINT = `${CLOUD_SETTINGS_ENDPOINT}/list-auto-generate`;
export const CLOUD_SAVE_CODE_SETTING_ENDPOINT = `${CLOUD_SETTINGS_ENDPOINT}/save-auto-generate`;
export const CLOUD_GET_ADVANCED_SETTING_ENDPOINT = `${CLOUD_SETTINGS_ENDPOINT}/get-advanced-setting`;
export const CLOUD_SAVE_ADVANCED_SETTING_ENDPOINT = `${CLOUD_SETTINGS_ENDPOINT}/save-advanced-setting`;

export const CLOUD_MERCHANT_ENDPOINT = '/merchant';
export const CLOUD_MERCHANT_GET_ENDPOINT = `${CLOUD_MERCHANT_ENDPOINT}/get`;
export const CLOUD_MERCHANT_SAVE_ENDPOINT = `${CLOUD_MERCHANT_ENDPOINT}/save`;

export const CLOUD_USER_ENDPOINT = '/user';
export const CLOUD_USER_LIST_ENDPOINT = `${CLOUD_USER_ENDPOINT}/list`;
export const CLOUD_USER_GET_ENDPOINT = `${CLOUD_USER_ENDPOINT}/get`;
export const CLOUD_USER_SAVE_ENDPOINT = `${CLOUD_USER_ENDPOINT}/save`;
export const CLOUD_USER_RESET_PASSWORD_ENDPOINT = `${CLOUD_USER_ENDPOINT}/reset-password`;
export const CLOUD_USER_RESET_PIN_ENDPOINT = `${CLOUD_USER_ENDPOINT}/reset-pincode`;
export const CLOUD_USER_REMOVE_ENDPOINT = `${CLOUD_USER_ENDPOINT}/delete`;

export const CLOUD_ROLE_ENDPOINT = '/role';
export const CLOUD_ROLE_ALL_ENDPOINT = `${CLOUD_ROLE_ENDPOINT}/all`;
export const CLOUD_ROLE_GET_ENDPOINT = `${CLOUD_ROLE_ENDPOINT}/get`;
export const CLOUD_ROLE_SAVE_ENDPOINT = `${CLOUD_ROLE_ENDPOINT}/save`;
export const CLOUD_ROLE_DELETE_ENDPOINT = `${CLOUD_ROLE_ENDPOINT}/delete`;
export const CLOUD_ROLE_PERMISSIONS_ENDPOINT = `${CLOUD_ROLE_ENDPOINT}/permission`;

export const CLOUD_STOCK_ENDPOINT = '/stock';
export const CLOUD_STOCK_LIST_ENDPOINT = `${CLOUD_STOCK_ENDPOINT}/list`;
export const CLOUD_STOCK_LIST_EXPORT_ENDPOINT = `${CLOUD_STOCK_LIST_ENDPOINT}/export`;
export const CLOUD_STOCK_HISTORY_ENDPOINT = `${CLOUD_STOCK_ENDPOINT}/history`;
export const CLOUD_STOCK_HISTORY_EXPORT_ENDPOINT = `${CLOUD_STOCK_HISTORY_ENDPOINT}/export`;
export const CLOUD_STOCK_HISTORY_RECALCULATE_ENDPOINT = `${CLOUD_STOCK_HISTORY_ENDPOINT}/recalculate`;

export const CLOUD_USER_REQUEST_ENDPOINT = '/request';
export const CLOUD_USER_REQUEST_LIST_ENDPOINT = `${CLOUD_USER_REQUEST_ENDPOINT}/list`;
export const CLOUD_USER_REQUEST_GET_ENDPOINT = `${CLOUD_USER_REQUEST_ENDPOINT}/get`;
export const CLOUD_USER_REQUEST_SAVE_ENDPOINT = `${CLOUD_USER_REQUEST_ENDPOINT}/save`;
export const CLOUD_USER_REQUEST_DELETE_ENDPOINT = `${CLOUD_USER_REQUEST_ENDPOINT}/delete`;
export const CLOUD_USER_REQUEST_PROGRESS_ENDPOINT = `${CLOUD_USER_REQUEST_ENDPOINT}/progress`;
export const CLOUD_USER_REQUEST_REVOKE_ENDPOINT = `${CLOUD_USER_REQUEST_ENDPOINT}/revoke`;

export const CLOUD_WAREHOUSE_IMPORT_ENDPOINT = '/warehouse-import';
export const CLOUD_WAREHOUSE_IMPORT_LIST_ENDPOINT = `${CLOUD_WAREHOUSE_IMPORT_ENDPOINT}/list`;
export const CLOUD_WAREHOUSE_IMPORT_GET_ENDPOINT = `${CLOUD_WAREHOUSE_IMPORT_ENDPOINT}/get`;
export const CLOUD_WAREHOUSE_IMPORT_SAVE_ENDPOINT = `${CLOUD_WAREHOUSE_IMPORT_ENDPOINT}/save`;
export const CLOUD_WAREHOUSE_IMPORT_DELETE_ENDPOINT = `${CLOUD_WAREHOUSE_IMPORT_ENDPOINT}/delete`;

export const CLOUD_WAREHOUSE_EXPORT_ENDPOINT = '/warehouse-export';
export const CLOUD_WAREHOUSE_EXPORT_LIST_ENDPOINT = `${CLOUD_WAREHOUSE_EXPORT_ENDPOINT}/list`;
export const CLOUD_WAREHOUSE_EXPORT_GET_ENDPOINT = `${CLOUD_WAREHOUSE_EXPORT_ENDPOINT}/get`;
export const CLOUD_WAREHOUSE_EXPORT_SAVE_ENDPOINT = `${CLOUD_WAREHOUSE_EXPORT_ENDPOINT}/save`;
export const CLOUD_WAREHOUSE_EXPORT_VOID_ENDPOINT = `${CLOUD_WAREHOUSE_EXPORT_ENDPOINT}/void`;
